openapi: "3.0.0"

info:
  version: "1.0"
  title: OWN TEXT 
  description: "Own text feature allows user to add his or her custom texts which can be used throughout the application has global elements.

        This included texts including AGBs (Terms and Conditions), Custom Document sections, Custom Standard texts to be used in various documents such as invoices, offers and purchase orders etc."
  contact:
    name: API team 
    url: 

servers:
 

paths:
  
      
components:
  

externalDocs:
  
